# Generated by Django 4.1 on 2022-08-19 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0020_rename_uploader_recipe_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='editor',
            field=models.ForeignKey(default='editor', on_delete=django.db.models.deletion.CASCADE, related_name='editor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
