# Generated by Django 4.1 on 2022-08-19 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_recipe_editor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='editor',
        ),
    ]
