# Generated by Django 4.1 on 2022-08-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_tag_recipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
