# Generated by Django 4.1 on 2022-08-22 01:38

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_alter_tag_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', recipes.models.TagField(default='Lucifer', max_length=200)),
            ],
        ),
    ]
