# Generated by Django 4.1 on 2022-08-22 01:40

from django.db import migrations
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0024_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=recipes.models.TagField(max_length=35, unique=True),
        ),
    ]
