# Generated by Django 4.1 on 2022-08-22 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0024_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='name',
        ),
    ]
