# Generated by Django 4.1 on 2022-08-22 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0026_test_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='email',
        ),
        migrations.RemoveField(
            model_name='test',
            name='password',
        ),
        migrations.RemoveField(
            model_name='test',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='test',
            name='username',
        ),
    ]
