# Generated by Django 4.1 on 2022-09-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipeingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=3000, null=True, verbose_name='Description (1 sentence)'),
        ),
    ]
