# Generated by Django 4.1 on 2022-08-16 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_rename_description_recipeingredient_description_raw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='description_raw',
            new_name='description',
        ),
    ]
