# Generated by Django 4.1 on 2022-08-16 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_rename_description_raw_recipeingredient_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='description',
        ),
    ]
