# Generated by Django 4.1 on 2022-09-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_servingunit_recipeservingunit_recipe_makes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeservingunit',
            name='description',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default='1. Churn the butter.', max_length=20000, verbose_name='Directions'),
        ),
    ]
