# Generated by Django 4.1 on 2022-10-08 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_remove_recipeservingunit_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='instructions',
            new_name='directions',
        ),
    ]
