# Generated by Django 4.1 on 2022-08-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_recipe_title_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='recipe',
            name='date_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last updated'),
        ),
    ]
