# Generated by Django 4.1 on 2022-10-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_recipe_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectioningredient',
            old_name='recipe_id',
            new_name='section_id',
        ),
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sectioningredient',
            name='order',
            field=models.FloatField(default=0),
        ),
    ]
