# Generated by Django 4.1 on 2022-08-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_recipe_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date_created',
            field=models.DateTimeField(verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='last_updated',
            field=models.DateTimeField(verbose_name='Last updated'),
        ),
    ]
