# Generated by Django 4.1 on 2022-10-08 21:31

from django.db import migrations


def migrate_recipeingredients(apps, schema_editor):
    Recipe = apps.get_model("recipes", "Recipe")
    RecipeIngredient = apps.get_model("recipes", "RecipeIngredient")
    Section = apps.get_model("recipes", "Section")
    SectionIngredient = apps.get_model("recipes", "SectionIngredient")
    Ingredient = apps.get_model("recipes", "Ingredient")

    all_recipes_list = Recipe.objects.all()

    sections_to_create = []
    section_ingredients_to_create = []
    for r in all_recipes_list:
        ri_list = RecipeIngredient.objects.filter(recipe_id = r.id)
        section = Section(name="Ingredients", order=0, recipe_id=r)

        for ri in ri_list:
            section_ingredient = SectionIngredient(
                    ingredient_id=ri.ingredient_id,
                    amount=ri.amount,
                    unit=ri.unit,
                    description=ri.description,
                    section_id=section)
            section_ingredients_to_create.append(section_ingredient)

        sections_to_create.append(section)

    Section.objects.bulk_create(sections_to_create)
    SectionIngredient.objects.bulk_create(section_ingredients_to_create)

def down(apps, schema_editor):
    Section = apps.get_model("recipes", "Section")
    SectionIngredient = apps.get_model("recipes", "SectionIngredient")

    Section.objects.all().delete()
    SectionIngredient.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
            ('recipes', '0013_rename_recipe_id_sectioningredient_section_id_and_more'),
            ]

    operations = [
            migrations.RunPython(migrate_recipeingredients, down)
            ]
