# Generated by Django 4.1 on 2022-10-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20221008_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(default='Ingredients', max_length=400),
        ),
    ]
