# Generated by Django 4.1 on 2022-10-08 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_alter_section_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='recipes.recipe'),
        ),
    ]
