# Generated by Django 4.1 on 2022-10-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_alter_section_recipe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
