# Generated by Django 4.1 on 2022-08-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_remove_recipeingredient_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
    ]
