# Generated by Django 4.1 on 2022-08-19 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_recipe_title_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='title_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
