# Generated by Django 4.1 on 2022-08-19 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_alter_recipe_date_created_alter_recipe_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date published'),
        ),
    ]
