# Generated by Django 4.1 on 2022-08-19 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_alter_recipe_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='last_updated',
        ),
    ]
