# Generated by Django 4.1 on 2022-08-22 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_rename_uploader_recipe_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default='1. Churn the butter.', max_length=20000),
        ),
    ]
